//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPZONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public string MaDH { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayDH { get; set; }
        public Nullable<double> TriGia { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public string SDTNguoiNhan { get; set; }
        public string HTTT { get; set; }
        public string TrinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
